[package]
name = "blkchn_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.4"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
sha2 = "0.9.8"
chrono = "0.4.19"
